<!DOCTYPE html>
<html>
<head>
    <title>Информация о книге</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <h1 class="mt-5">Информация о книге</h1>
    <div class="card mt-4">
        <div class="card-body">
            <h5 class="card-title">Название: ${book.name}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Автор: ${book.author}</h6>
            <p class="card-text">Описание: ${book.description}</p>
        </div>
    </div>
</div>ъ
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>